version: "3"

services:

  backend:
    image: bot-back:1
    container_name: bot-back
    volumes:
      - media:/app/db.sqlite
    ports:
      - 3421:3421
    networks:
      - server
  bot:
    image: bot:1
    container_name: bot
    depends_on:
      - backend
    networks:
      - server
volumes:
  media:

networks:
  server:
