# Generated by Django 4.1.7 on 2023-08-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.BigIntegerField(verbose_name="tg id")),
                (
                    "username",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Ник в тг"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Имя в тг"
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Фамилия в тг"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("A_min", models.FloatField()),
                ("A_max", models.FloatField()),
                ("dB", models.FloatField()),
                ("result", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.telegramuser",
                    ),
                ),
            ],
        ),
    ]
