# Generated by Django 4.2.4 on 2023-09-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_calculation_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculation',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
