# Generated by Django 4.2.4 on 2023-09-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_calculation_delete_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(unique=True, verbose_name='tg id')),
                ('username', models.CharField(max_length=256, null=True, verbose_name='Ник в тг')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='Имя в тг')),
                ('second_name', models.CharField(max_length=256, null=True, verbose_name='Фамилия в тг')),
                ('age', models.IntegerField()),
                ('course', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser')),
            ],
        ),
    ]
