# Generated by Django 4.2.5 on 2023-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_telegramuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='course',
            field=models.IntegerField(default=1),
        ),
    ]
