# Generated by Django 4.2.5 on 2023-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_telegramuser_age_alter_telegramuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
