# Generated by Django 4.2.5 on 2023-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_telegramuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
